database:
  url: ${DATABASE_URL}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 20
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
  liquibase:
    change-log: ${changeLogFile}
    database-change-log-table: ${databaseChangeLogTableName}
    database-change-log-lock-table: ${databaseChangeLogLockTableName}
