database:
  url: 192.168.49.2:30966/expense-tracker-dev
  user: pgUser
  password: pgPassword

spring:
  jpa.properties.hibernate:
    generate_statistics: true
    show_sql: true
    format_sql: true