spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
  datasource:
    username: pgUser
    password: pgPassword

