spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 20
  liquibase:
    change-log: ${changeLogFile}
    database-change-log-table: ${databaseChangeLogTableName}
    database-change-log-lock-table: ${databaseChangeLogLockTableName}

management:
  endpoints.web.exposure.include:
    - health
    - info
    - env
    - liquibase
    - loggers
  endpoint.health.show-details: always
  info:
    os.enabled: true
    java.enabled: true
    env.enabled: true

one-password:
  endpoint: http://vault.tools.com
  access-token: ${OP_TOKEN}
