spring:
  datasource.url: jdbc:postgresql://localhost:5432/expense-tracker-dev
  jpa.properties.hibernate:
    generate_statistics: true
    show_sql: true
    format_sql: true

logging.level.org.hibernate.type: trace