openapi: '3.0.3'

servers:
  - url: http://localhost:4010
    description: "Mocked server"
  - url: http://localhost:8080
    description: "Local server"
  - url: http://localhost:8081
    description: "Production server"

info:
  version: 1.0.0-SNAPSHOT
  title: Expense Tracker API Contract

paths:
  $ref: "./paths/_index.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
