openapi: '3.0.3'

servers:
  - url: http://localhost:4010
    description: "Mocked server"
  - url: http://localhost:8080
    description: "Local server"
  - url: http://localhost:8081
    description: "Production server"

info:
  version: 0.0.5-SNAPSHOT
  title: Expense Tracker API Contract

paths:
  /purchases:
    $ref: './paths/purchases/purchases.yaml'
  /purchases/{purchaseId}:
    $ref: './paths/purchases/purchase.yaml'
  /purchases/products/names:
    $ref: './paths/purchases/products/names.yaml'
  /purchases/shops:
    $ref: './paths/purchases/shops/shops.yaml'
  /purchases/categories:
    $ref: './paths/purchases/categories/categories.yaml'

components:
  schemas:
    PurchaseDto:
      $ref: './schemas/purchases/PurchaseDto.yaml'
    ProductsList:
      $ref: './schemas/purchases/products/ProductsList.yaml'
    ProductNamesList:
      $ref: './schemas/purchases/products/ProductNamesList.yaml'
    ProductDto:
      $ref: './schemas/purchases/products/ProductDto.yaml'
    ShopsList:
      $ref: './schemas/purchases/shops/ShopsList.yaml'
    ShopDto:
      $ref: './schemas/purchases/shops/ShopDto.yaml'
    CategoriesList:
      $ref: './schemas/purchases/categories/CategoriesList.yaml'
    CategoryDto:
      $ref: './schemas/purchases/categories/CategoryDto.yaml'
    ErrorMessage:
      $ref: './schemas/common/ErrorMessage.yaml'
    ValidationError:
      $ref: './schemas/common/ValidationError.yaml'

x-json-schema-faker:
  min-items: 2
  max-items: 10