openapi: '3.0.3'

servers:
  - url: http://localhost:4010
    description: "Mocked server"
  - url: http://localhost:8080
    description: "Local server"
  - url: http://localhost:8081
    description: "Production server"

info:
  version: 0.0.5-SNAPSHOT
  title: Expense Tracker API Contract

paths:
  /purchases:
    $ref: './paths/purchases/purchases.yaml'
  /purchases/{purchaseId}:
    $ref: './paths/purchases/purchase.yaml'
  /products/names:
    $ref: './paths/products/names.yaml'
  /shops:
    $ref: './paths/shops/shops.yaml'
  /categories:
    $ref: './paths/categories/categories.yaml'

components:
  schemas:
    PurchasePage:
      $ref: './schemas/purchases/PurchasePage.yaml'
    PurchaseDto:
      $ref: './schemas/purchases/PurchaseDto.yaml'
    AddEditPurchaseRequest:
      $ref: './schemas/purchases/AddEditPurchaseRequest.yaml'

    ProductList:
      $ref: './schemas/products/ProductList.yaml'
    ProductDto:
      $ref: './schemas/products/ProductDto.yaml'
    AddEditProductRequest:
      $ref: './schemas/products/AddEditProductRequest.yaml'
    AddEditProductRequestList:
      $ref: './schemas/products/AddEditProductRequestList.yaml'
    ProductNamesList:
      $ref: './schemas/products/ProductNamesList.yaml'

    ShopList:
      $ref: './schemas/shops/ShopList.yaml'
    ShopDto:
      $ref: './schemas/shops/ShopDto.yaml'
    AddShopRequest:
      $ref: './schemas/shops/AddShopRequest.yaml'

    CategoryList:
      $ref: './schemas/categories/CategoryList.yaml'
    CategoryDto:
      $ref: './schemas/categories/CategoryDto.yaml'
    AddCategoryRequest:
      $ref: './schemas/categories/AddCategoryRequest.yaml'

    BulkDeleteRequest:
      $ref: './schemas/common/BulkDeleteRequest.yaml'

    ErrorMessage:
      $ref: './schemas/common/ErrorMessage.yaml'
    ValidationError:
      $ref: './schemas/common/ValidationError.yaml'

x-json-schema-faker:
  min-items: 2
  max-items: 10