version: "3.8"

services:
  expense-tracker:
    image: expense-tracker
    container_name: expense-tracker
    volumes:
      - /var/expense-tracker:/epxense-tracker
    environment:
      TZ: 'UTC'
      SPRING_PROFILES_ACTIVE: 'prod'
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    user: $DOCKER_USR:$DOCKER_USR
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=pgUser
      - POSTGRES_PASSWORD=pgPassword
    volumes:
      - /var/postgres:/data/db
    ports:
      - '5432:5432'
    user: $DOCKER_USR:$DOCKER_USR
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=maciekqwertyzaqwsx@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgAdminPassword
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "9090:80"
    volumes:
      - /var/pgadmin4:/var/lib/pgadmin
    user: $DOCKER_USR:$DOCKER_USR
    restart: unless-stopped
