apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-tracker-persistent-volume-claim
spec:
  volumeName: expense-tracker-persistent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi