apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-tracker-pv
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: expense-tracker-pvc
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/apps/expense-tracker"