apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
  labels:
    app: expense-tracker
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker
          image: localhost:5000/expense-tracker:0.1.5
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: expense-tracker-storage
              mountPath: /app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TZ
              value: "UTC"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-configuration-test
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-configuration-test
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-configuration-test
                  key: database
            - name: DATABASE_URL
              value: "postgres-postgresql:5432/$(DATABASE_NAME)"
      volumes:
        - name: expense-tracker-storage
          persistentVolumeClaim:
            claimName: expense-tracker-pvc
      securityContext:
        fsGroup: 1001