apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-tracker-pvc
spec:
  volumeName: expense-tracker-pv
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi