apiVersion: v1
kind: PersistentVolume
metadata:
  name: fintracker-pv
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: fintracker-pvc
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/apps/fintracker"
