apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fintracker-pvc
spec:
  volumeName: fintracker-pv
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
