openapi: '3.0.3'

required:
  - id
  - date
  - shop
  - purchases

properties:
  id:
    type: string
    format: uuid
  date:
    type: string
    format: date
  shop:
    $ref: './shops/ShopDto.yaml'
  purchases:
    type: array
    items:
      $ref: './PurchaseDto.yaml'